=== delta3d/delta3d/tags/TEST_REL-2.7.3/delta3d/demos/fireFighter/FireFighterProject/map.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="delta3dMap"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Delta3D map save file schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="prefab" type="PrefabType"/>
  
  <xsd:complexType name="PrefabType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="actors" type="ActorsType"/>
    </xsd:sequence>
  </xsd:complexType>

  
  <xsd:element name="map" type="MapType"/>

  <xsd:complexType name="MapType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="libraries" type="LibrariesType"/>
      <xsd:element name="events" type="EventsType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="actors" type="ActorsType"/>
      <xsd:element name="groups" type="GroupsType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HeaderType">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>     
      <xsd:element name="waypointFileName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="createNavMesh" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="author"   type="xsd:string"/>
      <xsd:element name="comment"  type="xsd:string" minOccurs="0"/>
      <xsd:element name="copyright" type="xsd:string" minOccurs="0"/>
      <xsd:element name="createTimestamp" type="xsd:dateTime"/>
      <xsd:element name="lastUpdateTimestamp" type="xsd:dateTime"/>
      <xsd:element name="editorVersion" type="xsd:string"/>
      <!-- map won't validate unless the version number is correct -->
      <xsd:element name="schemaVersion" type="xsd:string" fixed="1.0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="LibrariesType">
    <xsd:sequence>
      <xsd:element name="library" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="EventsType">
    <xsd:sequence>
      <xsd:element name="event" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ActorsType">
    <xsd:sequence>
      <xsd:element name="environmentActor" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="actor" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="type" type="xsd:string" />
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>

            <xsd:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType"/>

          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="PropertyType">
    <xsd:sequence>
        <xsd:element name="name" type="xsd:string" />
        <xsd:choice>
          <xsd:element name="string" type="xsd:string" />
          <xsd:element name="enumerated" type="xsd:string"/>
          <xsd:element name="float" type="xsd:float"/>
          <xsd:element name="double" type="xsd:double"/>
          <xsd:element name="integer" type="xsd:int"/>
          <xsd:element name="long" type="xsd:long"/>
          <xsd:element name="vec4" type="Vec4Type" />
          <xsd:element name="vec3" type="Vec3Type" />
          <xsd:element name="vec2" type="Vec2Type"/>
          <xsd:element name="boolean" type="xsd:boolean"/>
          <xsd:element name="colorRGB" type="ColorRGBType"/>
          <xsd:element name="colorRGBA" type="ColorRGBAType"/>
          <xsd:sequence>
            <xsd:element name="resourceType" type="xsd:string" />
            <xsd:element name="resourceDisplayName" type="xsd:string" />
            <xsd:element name="resource" type="xsd:string" />
          </xsd:sequence>
          <xsd:element name="actorId" type="xsd:string" />
          <xsd:element name="group" type="GroupType"/>
          <xsd:element name="gameevent" type="xsd:string"/>
        </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="GroupsType">
    <xsd:sequence>
      <xsd:element name="group" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="actor" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="GroupType">
    <xsd:sequence>
        <xsd:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="PropertyType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Vec2Type">
    <xsd:all>
      <xsd:element name="value1" type="xsd:double" />
      <xsd:element name="value2" type="xsd:double" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="Vec3Type">
    <xsd:all>
      <xsd:element name="value1" type="xsd:double" />
      <xsd:element name="value2" type="xsd:double" />
      <xsd:element name="value3" type="xsd:double" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="Vec4Type">
    <xsd:all>
      <xsd:element name="value1" type="xsd:double" />
      <xsd:element name="value2" type="xsd:double" />
      <xsd:element name="value3" type="xsd:double" />
      <xsd:element name="value4" type="xsd:double" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="ColorRGBType">
    <xsd:all>
      <xsd:element name="valueR" type="xsd:float" />
      <xsd:element name="valueG" type="xsd:float" />
      <xsd:element name="valueB" type="xsd:float" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="ColorRGBAType">
    <xsd:all>
      <xsd:element name="valueR" type="xsd:float" />
      <xsd:element name="valueG" type="xsd:float" />
      <xsd:element name="valueB" type="xsd:float" />
      <xsd:element name="valueA" type="xsd:float" />
    </xsd:all>
  </xsd:complexType>

</xsd:schema>

=== delta3d/delta3d/branches/delta3d-alion-IITSEC-14-11-2006/demos/fireFighter/FireFighterProject/maps/IntroMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="delta3dMap" xsi:schemaLocation="delta3dMap map.xsd">
    <header>
        <name>IntroMap</name>
        <description>This is the intro map for the revised Fire Fighter application. </description>
        <author></author>
        <comment></comment>
        <copyright></copyright>
        <createTimestamp>2006-10-11T11:21:57.0-05:00</createTimestamp>
        <lastUpdateTimestamp>2006-10-11T13:43:49.0-05:00</lastUpdateTimestamp>
        <editorVersion>1.3.0</editorVersion>
        <schemaVersion>1.0</schemaVersion>
    </header>
    <libraries>
        <library>
            <name>fireFighter</name>
            <version></version>
        </library>
    </libraries>
    <actors>
        <actor>
            <type>FlySequence.FlySequence</type>
            <id>1c1ad7ea-2432-4ab6-9071-2f5147e4f07c</id>
            <name>Physical</name>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Box</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Collision Length</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Radius</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Type</name>
                <enumerated>NONE</enumerated>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Initial Ownership</name>
                <enumerated>Server Local</enumerated>
            </property>
            <property>
                <name>Mass</name>
                <float>4.188790321350098</float>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>ShaderGroup</name>
                <string></string>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>-0.809600</value1>
                    <value2>-46.540710</value2>
                    <value3>15.300002</value3>
                </vec3>
            </property>
        </actor>
        <actor>
            <type>DDGActor.DDGActor</type>
            <id>1f5b083f-5760-42d8-ab64-517de6d5220d</id>
            <name>DDGActor</name>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Box</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Collision Length</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Radius</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Type</name>
                <enumerated>NONE</enumerated>
            </property>
            <property>
                <name>CoordinateSystem</name>
                <enumerated>REL</enumerated>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Initial Ownership</name>
                <enumerated>Server Local</enumerated>
            </property>
            <property>
                <name>Mass</name>
                <float>4.188790321350098</float>
            </property>
            <property>
                <name>Model</name>
                <resourceType>StaticMeshes</resourceType>
                <resourceDisplayName>StaticMeshes:ddg:ddg-51.flt</resourceDisplayName>
                <resource>StaticMeshes:ddg:ddg-51.flt</resource>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>ShaderGroup</name>
                <string></string>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>100.000000</value3>
                </vec3>
            </property>
        </actor>
        <actor>
            <type>PlayerActor.PlayerActor</type>
            <id>583d7ca4-675a-4ac7-8fda-56ab049d7b3d</id>
            <name>PlayerActor</name>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Box</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Collision Length</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Radius</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Type</name>
                <enumerated>NONE</enumerated>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Initial Ownership</name>
                <enumerated>Server Local</enumerated>
            </property>
            <property>
                <name>Mass</name>
                <float>4.188790321350098</float>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>ShaderGroup</name>
                <string></string>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
        </actor>
    </actors>
</map>

=== delta3d/delta3d/tags/DCOS_RELEASE_2008_03_28/demos/TankTargetTutorial/StageProject/maps/mapone_playback.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="delta3dMap" xsi:schemaLocation="delta3dMap map.xsd">
    <header>
        <name>mapone_playback</name>
        <description>This map is used during playback. It has just the terrain in it. All other objects are created during the playback process. .</description>
        <author></author>
        <comment></comment>
        <copyright></copyright>
        <createTimestamp>2006-04-17T12:09:25.0-06:00</createTimestamp>
        <lastUpdateTimestamp>2006-06-22T21:33:27.0-05:00</lastUpdateTimestamp>
        <editorVersion>1.1.0</editorVersion>
        <schemaVersion>1.0</schemaVersion>
    </header>
    <libraries>
        <library>
            <name>TutorialLibrary</name>
            <version></version>
        </library>
    </libraries>
    <events>
        <event>
            <id>0e2800fa-be9f-4275-ab58-89bed75af2ad</id>
            <name>SpeedBoost</name>
            <description>Give the tank a small speed boost (+5) - this boost can exceed the speed cap.</description>
        </event>
        <event>
            <id>253320d0-841f-4c71-ab09-4546e0632269</id>
            <name>TestShaders</name>
            <description>A test message to allow us to reset our shaders. Just example code for how to manipulate shaders.</description>
        </event>
        <event>
            <id>541d83a1-748a-4957-93e1-048a157ae9f5</id>
            <name>ToggleEngine</name>
            <description>Toggles the tank engine on and off.</description>
        </event>
        <event>
            <id>675b8c02-a753-4aaa-8274-9a7847a66fa5</id>
            <name>TankFired</name>
            <description>The tank fired a shot.  The blimps listen for this and check to see if they are the current target.  If so, they take damage, else they ignore.</description>
        </event>
        <event>
            <id>e4082496-0afe-4398-a554-aa469e3c84ac</id>
            <name>ResetStuff</name>
            <description>Sort of restarts the level. Blimps come back alive, the tank goes back to home position, and you can blow em all up again!</description>
        </event>
    </events>
    <actors>
        <actor>
            <type>dtcore.Static Mesh</type>
            <id>7c47d096-403b-4d72-8c97-666818541b25</id>
            <name>Terrain</name>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Box</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Collision Length</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Radius</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Type</name>
                <enumerated>NONE</enumerated>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Mass</name>
                <float>0.1000000014901161</float>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>3.699999</value1>
                    <value2>0.000010</value2>
                    <value3>0.000010</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>3.000000</value1>
                    <value2>3.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>-1.547338</value1>
                    <value2>21.363609</value2>
                    <value3>-16.299416</value3>
                </vec3>
            </property>
            <property>
                <name>static mesh</name>
                <resourceType>StaticMeshes</resourceType>
                <resourceDisplayName>terrain_simple.ive</resourceDisplayName>
                <resource>StaticMeshes::terrain_simple.ive</resource>
            </property>
        </actor>
    </actors>
</map>
