=== delta3d/delta3d/tags/TEST_REL-2.7.3/delta3d/demos/fireFighter/FireFighterProject/map.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="delta3dMap"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Delta3D map save file schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="prefab" type="PrefabType"/>
  
  <xsd:complexType name="PrefabType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="actors" type="ActorsType"/>
    </xsd:sequence>
  </xsd:complexType>

  
  <xsd:element name="map" type="MapType"/>

  <xsd:complexType name="MapType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="libraries" type="LibrariesType"/>
      <xsd:element name="events" type="EventsType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="actors" type="ActorsType"/>
      <xsd:element name="groups" type="GroupsType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HeaderType">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>     
      <xsd:element name="waypointFileName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="createNavMesh" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="author"   type="xsd:string"/>
      <xsd:element name="comment"  type="xsd:string" minOccurs="0"/>
      <xsd:element name="copyright" type="xsd:string" minOccurs="0"/>
      <xsd:element name="createTimestamp" type="xsd:dateTime"/>
      <xsd:element name="lastUpdateTimestamp" type="xsd:dateTime"/>
      <xsd:element name="editorVersion" type="xsd:string"/>
      <!-- map won't validate unless the version number is correct -->
      <xsd:element name="schemaVersion" type="xsd:string" fixed="1.0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="LibrariesType">
    <xsd:sequence>
      <xsd:element name="library" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="EventsType">
    <xsd:sequence>
      <xsd:element name="event" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ActorsType">
    <xsd:sequence>
      <xsd:element name="environmentActor" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="actor" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="type" type="xsd:string" />
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>

            <xsd:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType"/>

          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="PropertyType">
    <xsd:sequence>
        <xsd:element name="name" type="xsd:string" />
        <xsd:choice>
          <xsd:element name="string" type="xsd:string" />
          <xsd:element name="enumerated" type="xsd:string"/>
          <xsd:element name="float" type="xsd:float"/>
          <xsd:element name="double" type="xsd:double"/>
          <xsd:element name="integer" type="xsd:int"/>
          <xsd:element name="long" type="xsd:long"/>
          <xsd:element name="vec4" type="Vec4Type" />
          <xsd:element name="vec3" type="Vec3Type" />
          <xsd:element name="vec2" type="Vec2Type"/>
          <xsd:element name="boolean" type="xsd:boolean"/>
          <xsd:element name="colorRGB" type="ColorRGBType"/>
          <xsd:element name="colorRGBA" type="ColorRGBAType"/>
          <xsd:sequence>
            <xsd:element name="resourceType" type="xsd:string" />
            <xsd:element name="resourceDisplayName" type="xsd:string" />
            <xsd:element name="resource" type="xsd:string" />
          </xsd:sequence>
          <xsd:element name="actorId" type="xsd:string" />
          <xsd:element name="group" type="GroupType"/>
          <xsd:element name="gameevent" type="xsd:string"/>
        </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="GroupsType">
    <xsd:sequence>
      <xsd:element name="group" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="actor" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="GroupType">
    <xsd:sequence>
        <xsd:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="PropertyType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Vec2Type">
    <xsd:all>
      <xsd:element name="value1" type="xsd:double" />
      <xsd:element name="value2" type="xsd:double" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="Vec3Type">
    <xsd:all>
      <xsd:element name="value1" type="xsd:double" />
      <xsd:element name="value2" type="xsd:double" />
      <xsd:element name="value3" type="xsd:double" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="Vec4Type">
    <xsd:all>
      <xsd:element name="value1" type="xsd:double" />
      <xsd:element name="value2" type="xsd:double" />
      <xsd:element name="value3" type="xsd:double" />
      <xsd:element name="value4" type="xsd:double" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="ColorRGBType">
    <xsd:all>
      <xsd:element name="valueR" type="xsd:float" />
      <xsd:element name="valueG" type="xsd:float" />
      <xsd:element name="valueB" type="xsd:float" />
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="ColorRGBAType">
    <xsd:all>
      <xsd:element name="valueR" type="xsd:float" />
      <xsd:element name="valueG" type="xsd:float" />
      <xsd:element name="valueB" type="xsd:float" />
      <xsd:element name="valueA" type="xsd:float" />
    </xsd:all>
  </xsd:complexType>

</xsd:schema>

=== delta3d/delta3d/tags/REL-2.1.0_RC1/examples/data/demoMap/maps/TestAnim.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="delta3dMap" xsi:schemaLocation="delta3dMap map.xsd">
    <header>
        <name>TestAnim</name>
        <description></description>
        <author></author>
        <comment></comment>
        <copyright></copyright>
        <createTimestamp>2007-05-10T16:08:18.0-05:00</createTimestamp>
        <lastUpdateTimestamp>2007-05-16T15:54:37.0-05:00</lastUpdateTimestamp>
        <editorVersion>1.3.0</editorVersion>
        <schemaVersion>1.0</schemaVersion>
    </header>
    <libraries></libraries>
    <actors>
        <actor>
            <type>dtcore.Lights.Infinite Light</type>
            <id>6729376f-a271-4794-b263-a68f2f663d31</id>
            <name>defaultInfiniteLight</name>
            <property>
                <name>Enable</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>LightNum</name>
                <integer>0</integer>
            </property>
            <property>
                <name>Lighting Mode</name>
                <enumerated>GLOBAL</enumerated>
            </property>
            <property>
                <name>Ambient</name>
                <colorRGBA>
                    <valueR>0.509804</valueR>
                    <valueG>0.509804</valueG>
                    <valueB>0.509804</valueB>
                    <valueA>1.000000</valueA>
                </colorRGBA>
            </property>
            <property>
                <name>Diffuse</name>
                <colorRGBA>
                    <valueR>0.800000</valueR>
                    <valueG>0.800000</valueG>
                    <valueB>0.800000</valueB>
                    <valueA>1.000000</valueA>
                </colorRGBA>
            </property>
            <property>
                <name>Specular</name>
                <colorRGBA>
                    <valueR>0.050000</valueR>
                    <valueG>0.050000</valueG>
                    <valueB>0.050000</valueB>
                    <valueA>1.000000</valueA>
                </colorRGBA>
            </property>
            <property>
                <name>Direction</name>
                <vec3>
                    <value1>75.000000</value1>
                    <value2>0.000000</value2>
                    <value3>179.999985</value3>
                </vec3>
            </property>
        </actor>
        <actor>
            <type>dtanim.AnimationGameActor</type>
            <id>e39619c2-a9a1-4ad0-a973-a82a1a87d6a9</id>
            <name>CharacterEntity</name>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>-0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>-180.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>-1.967511</value1>
                    <value2>33.840588</value2>
                    <value3>6.299999</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Show Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Collision Type</name>
                <enumerated>NONE</enumerated>
            </property>
            <property>
                <name>Collision Radius</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Length</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Box</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Render Proxy Node</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Mass</name>
                <float>4.1887903</float>
            </property>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Initial Ownership</name>
                <enumerated>Server Local</enumerated>
            </property>
            <property>
                <name>ShaderGroup</name>
                <string>
            </string>
            </property>
            <property>
                <name>Skeletal Mesh</name>
                <resourceType>SkeletalMeshes</resourceType>
                <resourceDisplayName>SkeletalMeshes:marine.xml</resourceDisplayName>
                <resource>SkeletalMeshes:marine.xml</resource>
            </property>
        </actor>
        <actor>
            <type>dtcore.Static Mesh</type>
            <id>e6b14232-fbd0-4ffe-b2b2-75ea9df9d5a8</id>
            <name>GroundActor</name>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>19.999998</value2>
                    <value3>-0.000001</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Show Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Collision Type</name>
                <enumerated>MESH</enumerated>
            </property>
            <property>
                <name>Collision Radius</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Length</name>
                <float>0</float>
            </property>
            <property>
                <name>Collision Box</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Render Proxy Node</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Mass</name>
                <float>4.1887903</float>
            </property>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>static mesh</name>
                <resourceType>StaticMeshes</resourceType>
                <resourceDisplayName>terrain_simple.ive</resourceDisplayName>
                <resource>StaticMeshes:terrain_simple.ive</resource>
            </property>
        </actor>
    </actors>
</map>

=== delta3d/delta3d/trunk/delta3d/VisualStudio/examples/testMap/MyContext/maps/MyCoolMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="delta3dMap" xsi:schemaLocation="delta3dMap map.xsd">
    <header>
        <name>MyCoolMap</name>
        <description></description>
        <author></author>
        <comment></comment>
        <copyright></copyright>
        <createTimestamp>2005-07-20T15:24:07.0-05:00</createTimestamp>
        <lastUpdateTimestamp>2005-07-20T15:26:39.0-05:00</lastUpdateTimestamp>
        <editorVersion>0.1</editorVersion>
        <schemaVersion>1.0</schemaVersion>
    </header>
    <libraries></libraries>
    <actors>
        <actor>
            <type>dtcore.Static Mesh</type>
            <id>39c7f896-d8a9-493f-87dd-4d155cdf13b3</id>
            <name>StaticMesh0</name>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Mass</name>
                <float>4.18879</float>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>71.700005</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>-1.204427</value1>
                    <value2>6.992940</value2>
                    <value3>-0.995956</value3>
                </vec3>
            </property>
            <property>
                <name>static mesh</name>
                <resourceType>StaticMeshes</resourceType>
                <resourceDisplayName>StaticMeshes::uh-1n.ive</resourceDisplayName>
                <resource>StaticMeshes::uh-1n.ive</resource>
            </property>
        </actor>
        <actor>
            <type>dtcore.Static Mesh</type>
            <id>3ee83bce-267b-441e-ba2a-59b55c9c3373</id>
            <name>StaticMesh1</name>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Mass</name>
                <float>4.18879</float>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>-34.544418</value1>
                    <value2>17.843115</value2>
                    <value3>-1.023567</value3>
                </vec3>
            </property>
            <property>
                <name>static mesh</name>
                <resourceType>StaticMeshes</resourceType>
                <resourceDisplayName>StaticMeshes::cypress1.ive</resourceDisplayName>
                <resource>StaticMeshes::cypress1.ive</resource>
            </property>
        </actor>
        <actor>
            <type>dtcore.Environment.Sky Box</type>
            <id>4f0db0e3-80ab-4171-a446-168a8838dabb</id>
            <name>SkyBox</name>
            <property>
                <name>Back Texture</name>
                <resourceType>Textures</resourceType>
                <resourceDisplayName>Textures::back.jpg</resourceDisplayName>
                <resource>Textures::back.jpg</resource>
            </property>
            <property>
                <name>Bottom Texture</name>
                <resourceType>Textures</resourceType>
                <resourceDisplayName>Textures::bottom.jpg</resourceDisplayName>
                <resource>Textures::bottom.jpg</resource>
            </property>
            <property>
                <name>Front Texture</name>
                <resourceType>Textures</resourceType>
                <resourceDisplayName>Textures::front.jpg</resourceDisplayName>
                <resource>Textures::front.jpg</resource>
            </property>
            <property>
                <name>Left Texture</name>
                <resourceType>Textures</resourceType>
                <resourceDisplayName>Textures::left.jpg</resourceDisplayName>
                <resource>Textures::left.jpg</resource>
            </property>
            <property>
                <name>Right Texture</name>
                <resourceType>Textures</resourceType>
                <resourceDisplayName>Textures::right.jpg</resourceDisplayName>
                <resource>Textures::right.jpg</resource>
            </property>
            <property>
                <name>Top Texture</name>
                <resourceType>Textures</resourceType>
                <resourceDisplayName>Textures::top.jpg</resourceDisplayName>
                <resource>Textures::top.jpg</resource>
            </property>
        </actor>
        <actor>
            <type>dtcore.Terrain.Infinite Terrain</type>
            <id>f6dd81f9-0adf-46f8-a815-f4490f378e30</id>
            <name>infiniteTerrain</name>
            <property>
                <name>Build Distance</name>
                <float>3000</float>
            </property>
            <property>
                <name>Center of Gravity</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Collision Geometry</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Enable Dynamics</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Horizontal Scale</name>
                <float>0.01</float>
            </property>
            <property>
                <name>Mass</name>
                <float>4.18879</float>
            </property>
            <property>
                <name>Normal Rescaling</name>
                <boolean>true</boolean>
            </property>
            <property>
                <name>Rotation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>0.000000</value2>
                    <value3>0.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Scale</name>
                <vec3>
                    <value1>1.000000</value1>
                    <value2>1.000000</value2>
                    <value3>1.000000</value3>
                </vec3>
            </property>
            <property>
                <name>Segment Divisions</name>
                <integer>128</integer>
            </property>
            <property>
                <name>Segment Size</name>
                <float>1000</float>
            </property>
            <property>
                <name>Smooth Collision</name>
                <boolean>false</boolean>
            </property>
            <property>
                <name>Translation</name>
                <vec3>
                    <value1>0.000000</value1>
                    <value2>19.999998</value2>
                    <value3>-0.000001</value3>
                </vec3>
            </property>
            <property>
                <name>Vertical Scale</name>
                <float>0.1</float>
            </property>
        </actor>
    </actors>
</map>
