=== delta3d/delta3d/trunk/delta3d/data/HLAMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="hlaComponent"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Delta3D HLA Component configuration
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="hla" type="HLAMappingType"/>

  <xsd:complexType name="HLAMappingType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="libraries" type="LibrariesType"/>
      <xsd:element name="objects" type="ObjectsType"/>
      <xsd:element name="interactions" type="InteractionsType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HeaderType">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="disEntityTypes" type="xsd:boolean"/>
      <xsd:element name="disEntityTypeAttribute" type="xsd:string"/>
      <xsd:element name="author"   type="xsd:string"/>
      <xsd:element name="comment"  type="xsd:string" minOccurs="0"/>
      <xsd:element name="copyright" type="xsd:string" minOccurs="0"/>
      <!-- document won't validate unless the version number is correct -->
      <xsd:element name="schemaVersion" type="xsd:string" fixed="1.0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="LibrariesType">
    <xsd:sequence>
      <xsd:element name="actorLibrary" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="translatorLibrary" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ObjectsType">
    <xsd:sequence>
      <xsd:element name="object" minOccurs="0" maxOccurs="unbounded">  
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="extends" type="xsd:string"/>
        <xsd:complexType>
          <xsd:sequence>
            <xsd:choice>
	      <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="objectClass" type="xsd:string" />
                  <xsd:element name="actorType" type="xsd:string"/>
                  <xsd:element name="remoteOnly" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="disEntityEnum" minOccurs="0" maxOccurs="1" type="DISEntityEnumType"/>
                </xsd:sequence>
              </xsd:complexType>	             
              <xsd:element name="abstract" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="entityIdAttributeName" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
            <xsd:element name="attrToProp" minOccurs="0" maxOccurs="unbounded" type="OneToOneType"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="objectHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="objectClass" type="xsd:string" />
            <xsd:element name="disEntityEnum" minOccurs="0" maxOccurs="1" type="DISEntityEnumType"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="actorTypeHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="actorType" type="xsd:string"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="InteractionsType">
    <xsd:sequence>
      <xsd:element name="interaction" minOccurs="0" maxOccurs="unbounded">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="extends" type="xsd:string"/>
        <xsd:complexType>
          <xsd:sequence>
            <xsd:choice>
		        <xsd:complexType>
		          <xsd:sequence>
		            <xsd:element name="interactionClass" type="xsd:string" />
		            <xsd:element name="messageType" type="xsd:string"/>
		          </xsd:sequence>
		        </xsd:complexType>	             
              <xsd:element name="abstract" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="paramToParam" minOccurs="0" maxOccurs="unbounded" type="OneToOneType"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="interactionHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="interactionClass" type="xsd:string" />
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="messageHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="messageType" type="xsd:string"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DISEntityEnumType">
    <xsd:sequence>
       <xsd:element name="kind" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="domain" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="country" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="category" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="subcategory" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="specific" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="extra" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="OneToOneType">
    <xsd:sequence>
      <xsd:element name="hlaName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="hlaDataType" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
      <xsd:element name="hlaRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="gameName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="gameDataType" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
      <xsd:element name="gameRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="default" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      
      <xsd:element name="enumerationMapping" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="value" type="xsd:string">
    	        <xsd:attribute name="id" type="xsd:int"/>      	
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      
    </xsd:sequence>
  </xsd:complexType>


</xsd:schema>

=== delta3d/delta3d/trunk/delta3d/data/Federations/HLAMappingExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<hla  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HLAMapping.xsd">
        
    <header>
        <name>Test</name>
        <description>test mapping</description>
        <disEntityTypes>true</disEntityTypes> 
        <disEntityTypeAttribute>EntityType</disEntityTypeAttribute>
        <author>David Guthrie</author>
        <comment>This is for the unit tests</comment>
        <copyright>2010 Alion</copyright>
        <schemaVersion>1.0</schemaVersion>
    </header>
    
    <libraries>
      <actorLibrary>
        <name>testGameActorLibrary</name>
        <version>1.0</version>
      </actorLibrary>
    </libraries>
    
    <ddm>
      <enabled>true</enabled>
      <space name="Geographic">
         <property name="Friendly Region Type">GEOGRAPHIC_SPACE</property>
         <property name="Neutral Region Type">APP_SPACE_ONLY</property>
         <property name="Enemy Region Type">APP_SPACE_ONLY</property>
         <property name="App Space Min">0</property>
         <property name="App Space Max">199</property>
         <property name="X Subscription Range">10</property>
         <property name="Y Subscription Range">10</property>
         <property name="Friendly App Space">7</property>   
         <property name="Enemy App Space">8</property>      
         <property name="Neutral App Space">9</property>    
         <property name="Min Time Between Updates">0.25</property>
      </space>
      <space name="NoSuchSpace">
         <property name="hi">junk</property>
         <property name="another">rubbish</property>
      </space>
    </ddm>
    
    <objects>
        <object name="BaseEntity">
            <abstract/>
            <ddmSpace>Geographic</ddmSpace>
            <entityIdAttributeName>EntityIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>ENTITY_TYPE_ID</hlaName>
                <hlaDataType>ENTITY_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Entity Type</gameName>
                <gameDataType>ENUMERATION</gameDataType>
                <gameRequired>false</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>EntityIdentifier</hlaName>
                <hlaDataType>ENTITY_IDENTIFIER_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>sendingActorId</gameName>
                <gameDataType>ACTOR</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>DamageState</hlaName>
                <hlaDataType>UNSIGNED_INT_TYPE</hlaDataType>
                <hlaRequired>false</hlaRequired>
                <gameName>Damage State</gameName>
                <gameDataType>ENUMERATION</gameDataType>
                <gameRequired>false</gameRequired>
                <default>Destroyed</default>
                <enumerationMapping>
                    <value id="0">No Damage</value>
                    <value id="1">Damaged</value>
                    <value id="2">Damaged</value>
                    <value id="3">Destroyed</value>
                </enumerationMapping>
            </attrToProp>            
            <attrToProp>
                <hlaName>Orientation</hlaName>
                <hlaDataType>EULER_ANGLES_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Rotation</gameName>
                <gameDataType>VEC3</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>WorldLocation</hlaName>
                <hlaDataType>WORLD_COORDINATE_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Translation</gameName>
                <gameDataType>VEC3</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
        </object>

        <object extends="BaseEntity" name="Test Tank">
            <objectClass>BaseEntity.PhysicalEntity.Platform.GroundVehicle</objectClass>
            <actorType>TestHLA.Tank</actorType>
            <entityType>1.1.222.2.4.6.0</entityType>
            <!--disEntityEnum>
                <kind>1</kind>
                <domain>1</domain>
                <country>222</country>
                <category>2</category>
                <subcategory>4</subcategory>
                <specific>6</specific>
                <extra>0</extra>
            </disEntityEnum-->
            <attrToProp>
                <gameName>Mesh</gameName>   
                <gameDataType>StaticMeshes</gameDataType>
                <default>StaticMeshes:articulation_test.ive</default>
            </attrToProp>
            <attrToProp>
               <hlaName>ENTITY_TYPE_ID</hlaName>
               <hlaDataType>ENTITY_TYPE</hlaDataType>
               <hlaRequired>true</hlaRequired>
               <gameName>Entity Type As String</gameName>
               <gameDataType>STRING</gameDataType>
               <gameRequired>false</gameRequired>
            </attrToProp>
            <attrToProp>
               <hlaName>MAPPING_NAME</hlaName>
               <hlaDataType>STRING_TYPE</hlaDataType>
               <hlaRequired>false</hlaRequired>
               <gameName>Object Mapping Name</gameName>
               <gameDataType>STRING</gameDataType>
               <gameRequired>false</gameRequired>
            </attrToProp>
        </object>

        <object extends="BaseEntity" name="F18">
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Jet</actorType>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>225</country>
                <category>1</category>
                <subcategory>9</subcategory>
                <specific>4</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>VELOCITY_VECTOR_TYPE</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>            
        </object>

        <object extends="BaseEntity" name="localHelo">
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Helicopter</actorType>
            <localOnly>true</localOnly>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>222</country>
                <category>20</category>
                <subcategory>2</subcategory>
                <specific>6</specific>
                <extra>0</extra>
            </disEntityEnum>
            <ddmSpace>Another Space</ddmSpace>
            <entityIdAttributeName>EntityIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>VELOCITY_VECTOR_TYPE</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>            
        </object>

        <object extends="BaseEntity" name="remoteHelo">
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Helicopter</actorType>
            <remoteOnly>true</remoteOnly>
            <entityType>1.2.222.20.2.6.0</entityType>
            <ddmSpace>Another Space</ddmSpace>
            <entityIdAttributeName>EntityIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>VELOCITY_VECTOR_TYPE</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>            
        </object>

        <object>
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Jet</actorType>
            <remoteOnly>true</remoteOnly>
            <entityType>1.2.225.0.0.0.0</entityType>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>VELOCITY_VECTOR_TYPE</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>
            <!-- this is an example for the unit tests 
                 to handle.  The handler for VELOCITY_VECTOR_TYPE current 
                 doesn't support having three parameters. SPATIAL_TYPE does,
                 however, work with it.-->            
            <attrToProp>
                <hlaName>AccelerationVector</hlaName>
                <hlaDataType>VELOCITY_VECTOR_TYPE</hlaDataType>
                <parameter>
                   <gameName>accelX</gameName>
                   <gameDataType>FLOAT</gameDataType>
                </parameter>
                <parameter>
                   <gameName>accelY</gameName>
                   <gameDataType>FLOAT</gameDataType>
                </parameter>
                <parameter>
                   <gameName>accelZ</gameName>
                   <gameDataType>FLOAT</gameDataType>
                </parameter>
            </attrToProp>
        </object>

        <object>
            <objectClass>BaseEntity.PhysicalEntity.CulturalFeature</objectClass>
            <actorType>TestHLA.CulturalFeature</actorType>
            <remoteOnly>false</remoteOnly>
