=== delta3d/delta3d/tags/2011_06_23_A/data/HLAMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Delta3D HLA Component configuration
    </xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name='nonEmptyString'>
    <xsd:restriction base='xsd:normalizedString'>
      <xsd:minLength value='1'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="hla" type="HLAMappingType"/>

  <xsd:complexType name="HLAMappingType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="libraries" type="LibrariesType"/>
      <xsd:element name="ddm" type="DDMType"/>
      <xsd:element name="objects" type="ObjectsType"/>
      <xsd:element name="interactions" type="InteractionsType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HeaderType">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="disEntityTypes" type="xsd:boolean"/>
      <xsd:element name="disEntityTypeAttribute" type="xsd:string"/>
      <xsd:element name="author"   type="xsd:string"/>
      <xsd:element name="comment"  type="xsd:string" minOccurs="0"/>
      <xsd:element name="copyright" type="xsd:string" minOccurs="0"/>
      <!-- document won't validate unless the version number is correct -->
      <xsd:element name="schemaVersion" type="xsd:string" fixed="1.0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="LibrariesType">
    <xsd:sequence>
      <xsd:element name="actorLibrary" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:normalizedString"/>
            <xsd:element name="version" type="xsd:normalizedString"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="translatorLibrary" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:normalizedString"/>
            <xsd:element name="version" type="xsd:normalizedString"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DDMType">
    <xsd:sequence>
      <xsd:element name="enabled" type="xsd:boolean"/>
      <xsd:element name="space" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="property" minOccurs="0" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="name" use="required" type="nonEmptyString"/>
                  </xsd:extension>  
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
         <xsd:attribute name="name" use="required" type="nonEmptyString"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ObjectsType">
    <xsd:sequence>
      <xsd:element name="object" minOccurs="0" maxOccurs="unbounded">  
        <xsd:complexType>
          <xsd:sequence>
            <xsd:choice>
              <xsd:sequence>
                <xsd:element name="objectClass" type="xsd:normalizedString" />
                <xsd:element name="actorType" type="xsd:normalizedString"/>
                <xsd:choice>
                  <xsd:element name="remoteOnly" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="localOnly" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
                </xsd:choice>
                <xsd:choice>
                   <xsd:element name="disEntityEnum" minOccurs="0" maxOccurs="1" type="DISEntityEnumType"/>
                   <xsd:element name="entityType" minOccurs="0" maxOccurs="1" type="EntityTypeString"/>
                </xsd:choice>
              </xsd:sequence>
              <xsd:element name="abstract" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="ddmSpace" type="xsd:normalizedString" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="entityIdAttributeName" type="xsd:normalizedString" minOccurs="0" maxOccurs="1" />
            <xsd:element name="entityTypeAttributeName" type="xsd:normalizedString" minOccurs="0" maxOccurs="1" />
            <xsd:element name="attrToProp" minOccurs="0" maxOccurs="unbounded" type="OneToManyType"/>
          </xsd:sequence>
          <xsd:attribute name="name" type="xsd:normalizedString"/>
          <xsd:attribute name="extends" type="xsd:normalizedString"/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="objectHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="objectClass" type="xsd:normalizedString" />
            <xsd:element name="disEntityEnum" minOccurs="0" maxOccurs="1" type="DISEntityEnumType"/>
            <xsd:element name="entityType" minOccurs="0" maxOccurs="1" type="EntityTypeString"/>
            <xsd:element name="handler" type="xsd:normalizedString"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="actorTypeHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="actorType" type="xsd:string"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="InteractionsType">
    <xsd:sequence>
      <xsd:element name="interaction" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:choice>
              <xsd:sequence>
                <xsd:element name="interactionClass" type="xsd:normalizedString" />
                <xsd:element name="messageType" type="xsd:normalizedString"/>
              </xsd:sequence>
              <xsd:element name="abstract" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="ddmSpace" type="xsd:normalizedString" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="paramToParam" minOccurs="0" maxOccurs="unbounded" type="OneToManyType"/>
          </xsd:sequence>
          <xsd:attribute name="name" type="xsd:normalizedString"/>
          <xsd:attribute name="extends" type="xsd:normalizedString"/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="interactionHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="interactionClass" type="xsd:string" />
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="messageHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="messageType" type="xsd:string"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DISEntityEnumType">
    <xsd:sequence>
       <xsd:element name="kind" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="domain" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="country" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="category" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="subcategory" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="specific" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="extra" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="EntityTypeString">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="(([0-9])*\.){6}([0-9])*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="OneToManyType">
    <xsd:sequence>
      <xsd:element name="hlaName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="hlaDataType" minOccurs="0" maxOccurs="1">
         <xsd:complexType>
            <xsd:simpleContent>
               <xsd:extension base="xsd:string">
                  <xsd:attribute name="array" type="xsd:boolean"/>
               </xsd:extension>
            </xsd:simpleContent>
         </xsd:complexType>
      </xsd:element>
      <xsd:element name="hlaRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
      <xsd:choice>
         <xsd:sequence>
            <xsd:element name="gameName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="gameDataType" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
            <xsd:element name="gameRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="default" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="enumerationMapping" minOccurs="0" maxOccurs="1">
               <xsd:complexType>
                  <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                     <xsd:element name="value">
                        <xsd:complexType>
                           <xsd:simpleContent>
                              <xsd:extension base="xsd:string">
                                 <xsd:attribute name="id" type="xsd:string"/>
                              </xsd:extension>
                           </xsd:simpleContent>
                        </xsd:complexType>
                     </xsd:element>
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
         <xsd:element name="parameter" type="GameParamType" minOccurs="0" maxOccurs="unbounded" />
      </xsd:choice>

      
    </xsd:sequence>
  </xsd:complexType>

   <xsd:complexType name="GameParamType">
      <xsd:sequence>
         <xsd:element name="gameName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="gameDataType" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
         <xsd:element name="gameRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="default" type="xsd:string" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="enumerationMapping" minOccurs="0" maxOccurs="1">
            <xsd:complexType>
               <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                  <xsd:element name="value">
                     <xsd:complexType>
                        <xsd:simpleContent>
                           <xsd:extension base="xsd:string">
                              <xsd:attribute name="id" type="xsd:string"/>
                           </xsd:extension>
                        </xsd:simpleContent>
                     </xsd:complexType>
                  </xsd:element>
               </xsd:sequence>
            </xsd:complexType>
         </xsd:element>
      </xsd:sequence>
   </xsd:complexType>

</xsd:schema>

=== delta3d/delta3d/branches/2010_03_24_A/tests/data/BrokenHLAMappingOverloadingRemote.xml
<?xml version="1.0" encoding="UTF-8"?>

<hla  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HLAMapping.xsd">
        
    <header>
        <name>Test</name>
        <description>test mapping</description>
        <disEntityTypes>true</disEntityTypes> 
        <disEntityTypeAttribute>EntityType</disEntityTypeAttribute>
        <author>David Guthrie</author>
        <comment>This is for the unit tests</comment>
        <copyright>2006 Alion</copyright>
        <schemaVersion>1.0</schemaVersion>
    </header>
    
    <libraries>
      <actorLibrary>
        <name>testGameActorLibrary</name>
        <version>1.0</version>
      </actorLibrary>
    </libraries>
    
    <ddm>
      <enabled>true</enabled>
      <space name="Geographic">
         <property name="Friendly Region Type">GEOGRAPHIC_SPACE</property>
         <property name="Enemy Region Type">APP_SPACE_ONLY</property>
         <property name="Friendly App Space">74</property>
         <property name="Neutral App Space">11</property>
         <property name="App Space Min">0</property>
         <property name="App Space Max">199</property>
      </space>
      <space name="NoSuchSpace">
         <property name="hi">junk</property>
         <property name="another">rubbish</property>
      </space>
    </ddm>
    
    <objects>
        <object name="BaseEntity">
            <abstract/>
            <ddmSpace>Geographic</ddmSpace>
            <entityIdAttributeName>EntityIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>ENTITY_TYPE_ID</hlaName>
                <hlaDataType>ENTITY_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Entity Type</gameName>
                <gameDataType>ENUMERATION</gameDataType>
                <gameRequired>false</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>EntityIdentifier</hlaName>
                <hlaDataType>ENTITY_IDENTIFIER_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>sendingActorId</gameName>
                <gameDataType>ACTOR</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>DamageState</hlaName>
                <hlaDataType>UNSIGNED_INT_TYPE</hlaDataType>
                <hlaRequired>false</hlaRequired>
                <gameName>Damage State</gameName>
                <gameDataType>ENUMERATION</gameDataType>
                <gameRequired>false</gameRequired>
                <default>Destroyed</default>
                <enumerationMapping>
                    <value id="0">No Damage</value>
                    <value id="1">Damaged</value>
                    <value id="2">Damaged</value>
                    <value id="3">Destroyed</value>
                </enumerationMapping>
            </attrToProp>            
            <attrToProp>
                <hlaName>Orientation</hlaName>
                <hlaDataType>EULER_ANGLES_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Rotation</gameName>
                <gameDataType>VEC3</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>WorldLocation</hlaName>
                <hlaDataType>WORLD_COORDINATE_TYPE</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Translation</gameName>
                <gameDataType>VEC3</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
        </object>

        <object extends="BaseEntity" name="Test Tank">
            <objectClass>BaseEntity.PhysicalEntity.Platform.GroundVehicle</objectClass>
            <actorType>TestHLA.Tank</actorType>
            <disEntityEnum>
                <kind>1</kind>
                <domain>1</domain>
                <country>222</country>
                <category>2</category>
                <subcategory>4</subcategory>
                <specific>6</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <gameName>Mesh</gameName>   
                <gameDataType>StaticMeshes</gameDataType>
                <default>StaticMeshes:articulation_test.ive</default>
            </attrToProp>
            <attrToProp>
               <hlaName>ENTITY_TYPE_ID</hlaName>
               <hlaDataType>ENTITY_TYPE</hlaDataType>
               <hlaRequired>true</hlaRequired>
               <gameName>Entity Type As String</gameName>
               <gameDataType>STRING</gameDataType>
               <gameRequired>false</gameRequired>
            </attrToProp>
            <attrToProp>
               <hlaName>MAPPING_NAME</hlaName>
               <hlaDataType>STRING_TYPE</hlaDataType>
               <hlaRequired>false</hlaRequired>
               <gameName>Object Mapping Name</gameName>
               <gameDataType>STRING</gameDataType>
               <gameRequired>false</gameRequired>
            </attrToProp>
        </object>

        <object extends="BaseEntity" name="Test Tank can't override remote with same dis id">
            <objectClass>BaseEntity.PhysicalEntity.Platform.GroundVehicle</objectClass>
            <actorType>TestHLA.Jet</actorType>
            <disEntityEnum>
                <kind>1</kind>
                <domain>1</domain>
                <country>222</country>
                <category>2</category>
                <subcategory>4</subcategory>
                <specific>6</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <gameName>Mesh</gameName>   
                <gameDataType>StaticMeshes</gameDataType>
                <default>StaticMeshes:articulation_test.ive</default>
            </attrToProp>
            <attrToProp>
               <hlaName>ENTITY_TYPE_ID</hlaName>
               <hlaDataType>ENTITY_TYPE</hlaDataType>
               <hlaRequired>true</hlaRequired>
               <gameName>Entity Type As String</gameName>
               <gameDataType>STRING</gameDataType>
               <gameRequired>false</gameRequired>
            </attrToProp>
            <attrToProp>
               <hlaName>MAPPING_NAME</hlaName>
               <hlaDataType>STRING_TYPE</hlaDataType>
               <hlaRequired>false</hlaRequired>
               <gameName>Object Mapping Name</gameName>
               <gameDataType>STRING</gameDataType>
               <gameRequired>false</gameRequired>
            </attrToProp>
        </object>
   </objects>
   <interactions/>
</hla>

=== delta3d/delta3d/delta3d/data/Federations/HLAMappingExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<hla xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="hlaComponent"
     xsi:schemaLocation="hlaComponent HLAMapping.xsd">
        
    <header>
        <name>Test</name>
        <description>test mapping</description>
        <disEntityTypes>true</disEntityTypes> 
        <disEntityTypeAttribute>EntityType</disEntityTypeAttribute>
        <author>David Guthrie</author>
        <comment>This is for the unit tests</comment>
        <copyright>2006 Alion</copyright>
        <schemaVersion>1.0</schemaVersion>
    </header>
    
    <libraries>
      <actorLibrary>
        <name>testGameActorLibrary</name>
        <version>1.0</version>
      </actorLibrary>
    </libraries>
    
    <objects>
        <object name="BaseEntity">
            <abstract/>
            <entityIdAttributeName>EntityIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>EntityType</hlaName>
                <hlaDataType>Entity</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Entity Type</gameName>
                <gameDataType>ENUMERATION</gameDataType>
                <gameRequired>false</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>EntityIdentifier</hlaName>
                <hlaDataType>Entity Identifier</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>sendingActorId</gameName>
                <gameDataType>ACTOR</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
            <attrToProp>
                <hlaName>DamageState</hlaName>
                <hlaDataType>Unsigned Int</hlaDataType>
                <hlaRequired>false</hlaRequired>
                <gameName>Damage State</gameName>
                <gameDataType>ENUMERATION</gameDataType>
                <gameRequired>false</gameRequired>
                <default>Destroyed</default>
                <enumerationMapping>
                    <value id="0">No Damage</value>
                    <value id="1">Damaged</value>
                    <value id="2">Damaged</value>
                    <value id="3">Destroyed</value>
                </enumerationMapping>
            </attrToProp>            
            <attrToProp>
                <hlaName>Orientation</hlaName>
                <hlaDataType>Euler Angle</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Rotation</gameName>
                <gameDataType>VEC3</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
                <!-- this should be ignored -->
                <enumerationMapping>
                	<value id="0">No Damage</value>
                	<value id="1">Slight Damage</value>
                	<value id="2">Moderate Damage</value>
                	<value id="3">Destroyed</value>
                </enumerationMapping>
            </attrToProp>            
            <attrToProp>
                <hlaName>WorldLocation</hlaName>
                <hlaDataType>World Coordinate</hlaDataType>
                <hlaRequired>true</hlaRequired>
                <gameName>Translation</gameName>
                <gameDataType>VEC3</gameDataType>
                <gameRequired>true</gameRequired>
                <default></default>
            </attrToProp>            
        </object>
        <object extends="BaseEntity">
            <objectClass>BaseEntity.PhysicalEntity.Platform.GroundVehicle</objectClass>
            <actorType>TestHLA.Tank</actorType>
            <disEntityEnum>
                <kind>1</kind>
                <domain>1</domain>
                <country>222</country>
                <category>2</category>
                <subcategory>4</subcategory>
                <specific>6</specific>
                <extra>0</extra>
            </disEntityEnum>
        </object>

        <object extends="BaseEntity" name="F18">
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Jet</actorType>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>225</country>
                <category>1</category>
                <subcategory>9</subcategory>
                <specific>4</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>Velocity Vector</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>            
        </object>

        <object extends="BaseEntity">
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Helicopter</actorType>
            <remoteOnly>true</remoteOnly>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>222</country>
                <category>20</category>
                <subcategory>2</subcategory>
                <specific>6</specific>
                <extra>0</extra>
            </disEntityEnum>
            <entityIdAttributeName>HeloIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>Velocity Vector</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>            
        </object>

        <object>
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>TestHLA.Jet</actorType>
            <remoteOnly>true</remoteOnly>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>225</country>
                <category>0</category>
                <subcategory>0</subcategory>
                <specific>0</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <hlaName>VelocityVector</hlaName>
                <hlaDataType>Velocity Vector</hlaDataType>
                <gameName>Velocity Vector</gameName>
                <gameDataType>VEC3D</gameDataType>
                <default></default>
            </attrToProp>            
        </object>

        <object>
            <objectClass>TryingToMapTheJetBidirectionallyAgain</objectClass>
            <actorType>TestHLA.Jet</actorType>
            <remoteOnly>false</remoteOnly>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>225</country>
                <category>0</category>
                <subcategory>0</subcategory>
                <specific>0</specific>
                <extra>0</extra>
            </disEntityEnum>
        </object>
    </objects>
    
    <interactions>

    	<interaction name="DetonationLoc" >
    	    <abstract/>
    	    <paramToParam>
    	        <hlaName>DetonationLocation</hlaName>
    	        <hlaDataType>World Coordinate</hlaDataType>
    	        <hlaRequired>true</hlaRequired>
    	        <gameName>Location</gameName>
    	        <gameDataType>VEC3</gameDataType>
    	        <gameRequired>true</gameRequired>
    	    </paramToParam>
    	</interaction>

    	<interaction extends="DetonationLoc">
    	    <interactionClass>MunitionDetonation</interactionClass>
    	    <messageType>Restarted</messageType>
    	</interaction>

        <interaction>
           <interactionClass>WeaponFire</interactionClass>
           <messageType>Resumed</messageType>
           <paramToParam>
              <hlaName>FiringObjectIdentifier</hlaName>
              <hlaDataType>Entity Identifier</hlaDataType>
              <hlaRequired>true</hlaRequired>
              <gameName>aboutActorId</gameName>
              <gameDataType>ACTOR</gameDataType>
              <gameRequired>true</gameRequired>
           </paramToParam>
        </interaction>
    </interactions>


</hla>
