=== delta3d/delta3d/tags/2011_06_23_A/data/HLAMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Delta3D HLA Component configuration
    </xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name='nonEmptyString'>
    <xsd:restriction base='xsd:normalizedString'>
      <xsd:minLength value='1'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="hla" type="HLAMappingType"/>

  <xsd:complexType name="HLAMappingType">
    <xsd:sequence>
      <xsd:element name="header" type="HeaderType"/>
      <xsd:element name="libraries" type="LibrariesType"/>
      <xsd:element name="ddm" type="DDMType"/>
      <xsd:element name="objects" type="ObjectsType"/>
      <xsd:element name="interactions" type="InteractionsType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HeaderType">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="disEntityTypes" type="xsd:boolean"/>
      <xsd:element name="disEntityTypeAttribute" type="xsd:string"/>
      <xsd:element name="author"   type="xsd:string"/>
      <xsd:element name="comment"  type="xsd:string" minOccurs="0"/>
      <xsd:element name="copyright" type="xsd:string" minOccurs="0"/>
      <!-- document won't validate unless the version number is correct -->
      <xsd:element name="schemaVersion" type="xsd:string" fixed="1.0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="LibrariesType">
    <xsd:sequence>
      <xsd:element name="actorLibrary" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:normalizedString"/>
            <xsd:element name="version" type="xsd:normalizedString"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="translatorLibrary" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:normalizedString"/>
            <xsd:element name="version" type="xsd:normalizedString"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DDMType">
    <xsd:sequence>
      <xsd:element name="enabled" type="xsd:boolean"/>
      <xsd:element name="space" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="property" minOccurs="0" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="name" use="required" type="nonEmptyString"/>
                  </xsd:extension>  
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
         <xsd:attribute name="name" use="required" type="nonEmptyString"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ObjectsType">
    <xsd:sequence>
      <xsd:element name="object" minOccurs="0" maxOccurs="unbounded">  
        <xsd:complexType>
          <xsd:sequence>
            <xsd:choice>
              <xsd:sequence>
                <xsd:element name="objectClass" type="xsd:normalizedString" />
                <xsd:element name="actorType" type="xsd:normalizedString"/>
                <xsd:choice>
                  <xsd:element name="remoteOnly" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
                  <xsd:element name="localOnly" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
                </xsd:choice>
                <xsd:choice>
                   <xsd:element name="disEntityEnum" minOccurs="0" maxOccurs="1" type="DISEntityEnumType"/>
                   <xsd:element name="entityType" minOccurs="0" maxOccurs="1" type="EntityTypeString"/>
                </xsd:choice>
              </xsd:sequence>
              <xsd:element name="abstract" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="ddmSpace" type="xsd:normalizedString" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="entityIdAttributeName" type="xsd:normalizedString" minOccurs="0" maxOccurs="1" />
            <xsd:element name="entityTypeAttributeName" type="xsd:normalizedString" minOccurs="0" maxOccurs="1" />
            <xsd:element name="attrToProp" minOccurs="0" maxOccurs="unbounded" type="OneToManyType"/>
          </xsd:sequence>
          <xsd:attribute name="name" type="xsd:normalizedString"/>
          <xsd:attribute name="extends" type="xsd:normalizedString"/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="objectHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="objectClass" type="xsd:normalizedString" />
            <xsd:element name="disEntityEnum" minOccurs="0" maxOccurs="1" type="DISEntityEnumType"/>
            <xsd:element name="entityType" minOccurs="0" maxOccurs="1" type="EntityTypeString"/>
            <xsd:element name="handler" type="xsd:normalizedString"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="actorTypeHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="actorType" type="xsd:string"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="InteractionsType">
    <xsd:sequence>
      <xsd:element name="interaction" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:choice>
              <xsd:sequence>
                <xsd:element name="interactionClass" type="xsd:normalizedString" />
                <xsd:element name="messageType" type="xsd:normalizedString"/>
              </xsd:sequence>
              <xsd:element name="abstract" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="ddmSpace" type="xsd:normalizedString" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="paramToParam" minOccurs="0" maxOccurs="unbounded" type="OneToManyType"/>
          </xsd:sequence>
          <xsd:attribute name="name" type="xsd:normalizedString"/>
          <xsd:attribute name="extends" type="xsd:normalizedString"/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="interactionHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="interactionClass" type="xsd:string" />
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="messageHandler" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="messageType" type="xsd:string"/>
            <xsd:element name="handler" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DISEntityEnumType">
    <xsd:sequence>
       <xsd:element name="kind" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="domain" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="country" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="category" type="xsd:int" minOccurs="0" maxOccurs="1" />      
       <xsd:element name="subcategory" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="specific" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
       <xsd:element name="extra" type="xsd:int" minOccurs="0" maxOccurs="1"/>      
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="EntityTypeString">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="(([0-9])*\.){6}([0-9])*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="OneToManyType">
    <xsd:sequence>
      <xsd:element name="hlaName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="hlaDataType" minOccurs="0" maxOccurs="1">
         <xsd:complexType>
            <xsd:simpleContent>
               <xsd:extension base="xsd:string">
                  <xsd:attribute name="array" type="xsd:boolean"/>
               </xsd:extension>
            </xsd:simpleContent>
         </xsd:complexType>
      </xsd:element>
      <xsd:element name="hlaRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
      <xsd:choice>
         <xsd:sequence>
            <xsd:element name="gameName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="gameDataType" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
            <xsd:element name="gameRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="default" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="enumerationMapping" minOccurs="0" maxOccurs="1">
               <xsd:complexType>
                  <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                     <xsd:element name="value">
                        <xsd:complexType>
                           <xsd:simpleContent>
                              <xsd:extension base="xsd:string">
                                 <xsd:attribute name="id" type="xsd:string"/>
                              </xsd:extension>
                           </xsd:simpleContent>
                        </xsd:complexType>
                     </xsd:element>
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
         <xsd:element name="parameter" type="GameParamType" minOccurs="0" maxOccurs="unbounded" />
      </xsd:choice>

      
    </xsd:sequence>
  </xsd:complexType>

   <xsd:complexType name="GameParamType">
      <xsd:sequence>
         <xsd:element name="gameName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="gameDataType" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
         <xsd:element name="gameRequired" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="default" type="xsd:string" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="enumerationMapping" minOccurs="0" maxOccurs="1">
            <xsd:complexType>
               <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                  <xsd:element name="value">
                     <xsd:complexType>
                        <xsd:simpleContent>
                           <xsd:extension base="xsd:string">
                              <xsd:attribute name="id" type="xsd:string"/>
                           </xsd:extension>
                        </xsd:simpleContent>
                     </xsd:complexType>
                  </xsd:element>
               </xsd:sequence>
            </xsd:complexType>
         </xsd:element>
      </xsd:sequence>
   </xsd:complexType>

</xsd:schema>

=== delta3d/delta3d/branches/TRY-STAGEApp/demos/TankTargetTutorial/StageProject/Federations/HLAMapping.xml
<?xml version="1.0" encoding="UTF-8"?>

<hla xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="hlaComponent"
     xsi:schemaLocation="hlaComponent HLAMapping.xsd">

    <header>
        <name>Tutorial</name>
        <description>Tutorial HLA mapping</description>
        <disEntityTypes>true</disEntityTypes>
        <disEntityTypeAttribute>EntityType</disEntityTypeAttribute>
        <author>David Guthrie</author>
        <comment></comment>
        <copyright>2006 Alion Science and Technology</copyright>
        <schemaVersion>1.0</schemaVersion>
    </header>

    <libraries>
      <actorLibrary>
        <name>TutorialLibrary</name>
        <version>1.0</version>
      </actorLibrary>
    </libraries>

    <objects>
        <object name="BaseEntity">
            <abstract/>
            <entityIdAttributeName>EntityIdentifier</entityIdAttributeName>
            <attrToProp>
                <hlaName>Orientation</hlaName>
                <hlaDataType>EULER_ANGLES_TYPE</hlaDataType>
                <gameName>Rotation</gameName>
                <gameDataType>VEC3</gameDataType>
            </attrToProp>
            <attrToProp>
                <hlaName>WorldLocation</hlaName>
                <hlaDataType>WORLD_COORDINATE_TYPE</hlaDataType>
                <gameName>Translation</gameName>
                <gameDataType>VEC3</gameDataType>
            </attrToProp>
        </object>

        <object name="PhysicalEntity" extends="BaseEntity">
            <abstract/>
            <attrToProp>
                <hlaName>DamageState</hlaName>
                <hlaDataType>UNSIGNED_INT_TYPE</hlaDataType>
                <gameName>Current Health</gameName>
                <gameDataType>INT</gameDataType>
            </attrToProp>
            <attrToProp>
                <hlaName>Marking</hlaName>
                <hlaDataType>MARKING_TYPE</hlaDataType>
                <gameName>Name</gameName>
                <gameDataType>STRING</gameDataType>
            </attrToProp>
        </object>

        <object name="GroundVehicle" extends="PhysicalEntity">
            <abstract/>
        </object>

        <object name="Aircraft" extends="PhysicalEntity">
            <abstract/>
        </object>

        <object name="HoverTank" extends="GroundVehicle">
            <objectClass>BaseEntity.PhysicalEntity.Platform.GroundVehicle</objectClass>
            <actorType>MyActors.Tanks.Tank</actorType>
            <disEntityEnum>
                <kind>1</kind>
                <domain>1</domain>
                <country>222</country>
                <category>2</category>
                <subcategory>4</subcategory>
                <specific>3</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <gameName>static mesh</gameName>
                <gameDataType>StaticMeshes</gameDataType>
                <default>StaticMeshes::bmp_hover.ive</default>
            </attrToProp>
        </object>

        <object name="Blimp" extends="Aircraft">
            <objectClass>BaseEntity.PhysicalEntity.Platform.Aircraft</objectClass>
            <actorType>MyActors.Targets.KillableTarget</actorType>
            <remoteOnly>false</remoteOnly>
            <disEntityEnum>
                <kind>1</kind>
                <domain>2</domain>
                <country>225</country>
                <category>1</category>
                <subcategory>9</subcategory>
                <specific>3</specific>
                <extra>0</extra>
            </disEntityEnum>
            <attrToProp>
                <gameName>static mesh</gameName>
                <gameDataType>StaticMeshes</gameDataType>
                <default>StaticMeshes::happyBlimp.ive</default>
            </attrToProp>
            <attrToProp>
                <gameName>Scale</gameName>
                <gameDataType>VEC3</gameDataType>
                <default>0.5 0.5 0.5</default>
            </attrToProp>
       </object>

    </objects>

    <interactions>
    </interactions>
</hla>
