=== delta3d/delta3d/branches/TRY-OSG2.x/data/application.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" id="Application">

	<xs:simpleType name='nonEmptyString'>
		<xs:restriction base='xs:normalizedString'>
			<xs:minLength value='1'/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="PropertyType"  >
		<xs:simpleContent>
			<xs:extension base="xs:normalizedString">
				<xs:attribute name="Name" use="required" type="nonEmptyString" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="Application">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element name="Window">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="X" type="xs:string" use="required"/>
						<xs:attribute name="Y" type="xs:string" use="required"/>
						<xs:attribute name="Width" type="xs:string" use="required"/>
						<xs:attribute name="Height" type="xs:string" use="required"/>
						<xs:attribute name="PixelDepth" type="xs:integer" use="required"/>
						<xs:attribute name="RefreshRate" type="xs:integer" use="required"/>
						<xs:attribute name="ShowCursor" type="xs:boolean" use="required"/>
						<xs:attribute name="FullScreen" type="xs:boolean" use="required"/>
						<xs:attribute name="ChangeDisplayResolution" type="xs:boolean" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Scene">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required" form="unqualified"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Camera">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required" form="unqualified"/>
                        			<xs:attribute name="WindowInstance" type="xs:string" use="required" form="unqualified"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="View">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required" form="unqualified"/>
                        			<xs:attribute name="CameraInstance" type="xs:string" use="required" form="unqualified"/>
                        			<xs:attribute name="SceneInstance" type="xs:string" use="required" form="unqualified"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Log" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" form="unqualified"/>
						<xs:attribute name="Level" type="xs:string" use="required" form="unqualified"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="LibraryPath" minOccurs="0" maxOccurs="unbounded" type="xs:normalizedString" />
				<xs:element name="Properties" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
        				</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== delta3d/delta3d/tags/REL-2.8.0/examples/testApp/config.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<Application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="../../data/application.xsd">

   <!-- Window & View Settings -->
	<Window Name="testApp" X="100" Y="100" Width="1080" Height="720" PixelDepth="32" RefreshRate="60" ShowCursor="1" FullScreen="0" MultiSample="1" ChangeDisplayResolution="0"/>
	<Scene Name="defaultScene"/>
	<Camera Name="defaultCam" WindowInstance="testApp"/>
	<View Name="defaultView" CameraInstance="defaultCam" SceneInstance="defaultScene"/>
        <Log Name="animationtransitionplanner.cpp" Level="Warning"/>
   
   <Properties>
   <!-- Possible threading models:
	 SingleThreaded,
	 CullDrawThreadPerContext,
	 DrawThreadPerContext,
	 CullThreadPerCameraDrawThreadPerContext,
	 AutomaticSelection -->
   <Property Name="System.OSGThreadingModel">CullThreadPerCameraDrawThreadPerContext</Property>

   <Property Name="DeveloperMode">true</Property>
   <Property Name="GameManager.Statistics.Interval">0</Property>
   <Property Name="GameManager.Statistics.ToConsole">true</Property>

   <Property Name="System.SimFrameRate">30</Property>
   <Property Name="System.MaxTimeBetweenDraws">0.5</Property>
   <Property Name="System.UseFixedTimeStep">true</Property>
      
   <Property Name="dtPhysics.PhysicsEngine">Bullet</Property>
   <!--Property Name="dtPhysics.PalPluginPath">./bin/PalPlugins</Property-->
   <Property Name="dtPhysics.EnableStepPhysicsInBackground">true</Property>
   <!-- This is the number of steps the physics engine will use for solving
    constraints per engine substep -->
   <Property Name="dtPhysics.SolverIterationCount">20</Property>
   <Property Name="dtPhysics.TicksPerSecond">60</Property>
   <!-- This is the number of threads to run the physics on, which
         defaults to the number of cores you have, except that not all engines
         will run in a background thread.-->
   <Property Name="dtPhysics.NumProcessingElements">1</Property>
   <!-- The range from the main camera to use for debug-drawing
         the physics.  Setting this to 0 is infinite range.  Physics debug
         drawing has lots of overhead and is completely brute force, so if you
         have a large complex physics scene with lots of triangle mesh data,
         you should probably set this to something small or you likely won't be
         able to run at an interactive framerate. -->
   <Property Name="dtPhysics.DebugDrawRange">100.0</Property>
   </Properties>
   
</Application>

=== delta3d/delta3d/branches/DVTE07_Final_Release_Candidate_1_2007_09_10/demos/TankTargetTutorial/config.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no" ?>

<Application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="application.xsd">
    <Window Name="Delta3D Tank Target Tutorial" X="100" Y="100" Width="1280" Height="800" PixelDepth="24" RefreshRate="60" ShowCursor="1" FullScreen="0" ChangeDisplayResolution="0" />
    <Scene Name="defaultScene" />
    <Camera Name="defaultCam" WindowInstance="Delta3D Tank Target Tutorial" SceneInstance="defaultScene" />
    
    <Log Level="Error" />
    <Log Name="gameactor.cpp" Level="Warn" />

    <Properties>
      <Property Name="ProjectPath">.\StageProject</Property>
    </Properties>

</Application>

=== delta3d/delta3d/branches/BRANCH_1.X/demos/TankTargetTutorial/config.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no" ?>

<Application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="application.xsd">
    <Window Name="Delta3D IG" X="100" Y="100" Width="1280" Height="1024" PixelDepth="24" RefreshRate="60" ShowCursor="1" FullScreen="0" ChangeDisplayResolution="0" />
    <Scene Name="defaultScene" />
    <Camera Name="defaultCam" WindowInstance="Delta3D IG" SceneInstance="defaultScene" />
    
    <Log Level="Warn" />
    <Log Name="gameactor.cpp" Level="Warn" />

    <Properties>
      <Property Name="UseGPUCharacterSkinning">true</Property>
    </Properties>

</Application>
